const ACCES_TOKEN_SECRET = "ZAQ!2wsxCDE#";
const ACCES_TOKEN_LIFE = 1200;
const REFRESH_TOKEN_SECRET = "CDE#2wsxZAQ!";
const REFRESH_TOKEN_LIFE = 2592000;

module.exports = {
    ACCES_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET,
    ACCES_TOKEN_LIFE,
    REFRESH_TOKEN_LIFE
}