const ACCES_TOKEN_SECRET = "ZAQ!2wsxCDE#";
const ACCES_TOKEN_LIFE = 1200;
const REFRESH_TOKEN_SECRET = "CDE#2wsxZAQ!";
const REFRESH_TOKEN_LIFE = 2592000;
const RESET_TOKEN_SECRET = "VDFd_eer67cVw321sm)";
const RESET_TOKEN_LIFE = 600;

module.exports = {
    ACCES_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET,
    RESET_TOKEN_SECRET,
    ACCES_TOKEN_LIFE,
    REFRESH_TOKEN_LIFE,
    RESET_TOKEN_LIFE,
}